# -*- coding: utf-8 -*-
"""translator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12-kXDAMaOBBqYKtdE4HbtbhY-w_oSegw
"""

!pip install deep-translator gradio

from deep_translator import GoogleTranslator
import gradio as gr

def translate_text(text, target_language):
    try:
        translated = GoogleTranslator(
            source='auto',
            target=target_language
        ).translate(text)

        return translated

    except Exception as e:
        return f"Error: {str(e)}"

languages = {
    "Hindi": "hi",
    "French": "fr",
    "German": "de",
    "Spanish": "es",
    "Japanese": "ja",
    "Chinese": "zh-CN",
    "Arabic": "ar",
    "Russian": "ru",
    "English": "en"
}

interface = gr.Interface(
    fn=lambda text, lang: translate_text(text, languages[lang]),
    inputs=[
        gr.Textbox(lines=5, label="Enter Text"),
        gr.Dropdown(
            choices=list(languages.keys()),
            label="Select Language"
        )
    ],
    outputs=gr.Textbox(label="Translated Text"),
    title="AI Translator App",
    description="Translate text into multiple languages"
)

interface.launch()